/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.bloodbowl;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertEquals(3, 3);
    }
}
